--- #YAML:1.0
name:               Music-Tag
version:            0.36
abstract:           Interface for collecting information about music files.
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Options:  0.07
    Data::Dumper:     2
    Digest::SHA1:     2.11
    Encode:           2.12
    File::Copy:       0
    File::Spec:       3.24
    IO::File:         1.13
    Locale::Country:  2.07
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
